# Generated by Django 6.1 on 2026-08-09 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('membership', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialledger',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.paymentcategory'),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='membership.memberprofile'),
        ),
        migrations.AddField(
            model_name='financialledger',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='finance.paymentsubmission'),
        ),
    ]
