# Generated by Django 6.1 on 2026-08-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_paymentcategory_default_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
