# Generated by Django 6.1 on 2026-08-09 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialledger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentcategory',
            options={'verbose_name_plural': 'Payment Categories'},
        ),
        migrations.AlterModelOptions(
            name='paymentsubmission',
            options={},
        ),
        migrations.RenameField(
            model_name='paymentsubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='financialledger',
            name='description',
        ),
        migrations.RemoveField(
            model_name='financialledger',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='financialledger',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='financialledger',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='paymentcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentcategory',
            name='default_amount',
        ),
        migrations.RemoveField(
            model_name='paymentcategory',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='paymentsubmission',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='financialledger',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.paymentsubmission'),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='transaction_reference',
            field=models.CharField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialledger',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financialledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paymentcategory'),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='proof_of_payment',
            field=models.FileField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
