# Generated by Django 6.1 on 2026-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_paymentcategory_is_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=0.0),
            preserve_default=False,
        ),
    ]
